// <auto-generated />
using System;
using LMPTS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMPTS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260630171112_AddressAdded")]
    partial class AddressAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AttendanceRecord", b =>
                {
                    b.Property<int>("AttendanceRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceRecordId"));

                    b.Property<DateOnly>("AttendanceDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Bonus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DailyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Deduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LaborId")
                        .HasColumnType("int");

                    b.Property<decimal>("OvertimeHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OvertimeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalHoursWorked")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AttendanceRecordId");

                    b.HasIndex("LaborId");

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("LMPTS.Entities.Builder", b =>
                {
                    b.Property<int>("BuilderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BuilderId"));

                    b.Property<string>("BuilderType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContractorCount")
                        .HasColumnType("int");

                    b.Property<string>("GSTNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("PANNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredMobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupervisorCount")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BuilderId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Builders");
                });

            modelBuilder.Entity("LMPTS.Entities.BuilderContractor", b =>
                {
                    b.Property<int>("BuilderId")
                        .HasColumnType("int");

                    b.Property<int>("ContractorId")
                        .HasColumnType("int");

                    b.HasKey("BuilderId", "ContractorId");

                    b.HasIndex("ContractorId");

                    b.ToTable("BuilderContractors");
                });

            modelBuilder.Entity("LMPTS.Entities.Contractor", b =>
                {
                    b.Property<int>("ContractorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractorId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManagingSupervisorId")
                        .HasColumnType("int");

                    b.Property<string>("Specilization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ContractorId");

                    b.HasIndex("ManagingSupervisorId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Contractors");
                });

            modelBuilder.Entity("LMPTS.Entities.Labor", b =>
                {
                    b.Property<int>("LaborId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LaborId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContractorId")
                        .HasColumnType("int");

                    b.Property<int?>("ManagingSupervisorId")
                        .HasColumnType("int");

                    b.Property<int>("Skill")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LaborId");

                    b.HasIndex("ContractorId");

                    b.HasIndex("ManagingSupervisorId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Labours");
                });

            modelBuilder.Entity("LMPTS.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<int>("AbsentDays")
                        .HasColumnType("int");

                    b.Property<decimal>("AdvancePaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Bonus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DailyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Deduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HalfDays")
                        .HasColumnType("int");

                    b.Property<int>("LaborId")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OvertimeHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OvertimeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMode")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<int>("PresentDays")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalHoursWorked")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransactionReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("LaborId", "Month", "Year")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("LMPTS.Entities.Supervisor", b =>
                {
                    b.Property<int>("SupervisorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupervisorId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContractorId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SupervisorId");

                    b.HasIndex("ContractorId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Supervisors");
                });

            modelBuilder.Entity("LMPTS.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LMPTS.Entities.UserOtp", b =>
                {
                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MobileNumber");

                    b.ToTable("UserOtps");
                });

            modelBuilder.Entity("AttendanceRecord", b =>
                {
                    b.HasOne("LMPTS.Entities.Labor", "Labor")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("LaborId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Labor");
                });

            modelBuilder.Entity("LMPTS.Entities.Builder", b =>
                {
                    b.HasOne("LMPTS.Entities.User", "User")
                        .WithOne("Builder")
                        .HasForeignKey("LMPTS.Entities.Builder", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMPTS.Entities.BuilderContractor", b =>
                {
                    b.HasOne("LMPTS.Entities.Builder", "Builder")
                        .WithMany("BuilderContractors")
                        .HasForeignKey("BuilderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMPTS.Entities.Contractor", "Contractor")
                        .WithMany("BuilderContractors")
                        .HasForeignKey("ContractorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Builder");

                    b.Navigation("Contractor");
                });

            modelBuilder.Entity("LMPTS.Entities.Contractor", b =>
                {
                    b.HasOne("LMPTS.Entities.Supervisor", "ManagingSupervisor")
                        .WithMany("ManagedContractors")
                        .HasForeignKey("ManagingSupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LMPTS.Entities.User", "User")
                        .WithOne("Contractor")
                        .HasForeignKey("LMPTS.Entities.Contractor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManagingSupervisor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMPTS.Entities.Labor", b =>
                {
                    b.HasOne("LMPTS.Entities.Contractor", "Contractor")
                        .WithMany("Labors")
                        .HasForeignKey("ContractorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMPTS.Entities.Supervisor", "ManagingSupervisor")
                        .WithMany("ManagedLabors")
                        .HasForeignKey("ManagingSupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LMPTS.Entities.User", "User")
                        .WithOne("Labor")
                        .HasForeignKey("LMPTS.Entities.Labor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contractor");

                    b.Navigation("ManagingSupervisor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMPTS.Entities.Payment", b =>
                {
                    b.HasOne("LMPTS.Entities.Labor", "Labor")
                        .WithMany("Payments")
                        .HasForeignKey("LaborId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Labor");
                });

            modelBuilder.Entity("LMPTS.Entities.Supervisor", b =>
                {
                    b.HasOne("LMPTS.Entities.Contractor", "Contractor")
                        .WithMany("Supervisors")
                        .HasForeignKey("ContractorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMPTS.Entities.User", "User")
                        .WithOne("Supervisor")
                        .HasForeignKey("LMPTS.Entities.Supervisor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contractor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMPTS.Entities.Builder", b =>
                {
                    b.Navigation("BuilderContractors");
                });

            modelBuilder.Entity("LMPTS.Entities.Contractor", b =>
                {
                    b.Navigation("BuilderContractors");

                    b.Navigation("Labors");

                    b.Navigation("Supervisors");
                });

            modelBuilder.Entity("LMPTS.Entities.Labor", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("LMPTS.Entities.Supervisor", b =>
                {
                    b.Navigation("ManagedContractors");

                    b.Navigation("ManagedLabors");
                });

            modelBuilder.Entity("LMPTS.Entities.User", b =>
                {
                    b.Navigation("Builder");

                    b.Navigation("Contractor");

                    b.Navigation("Labor");

                    b.Navigation("Supervisor");
                });
#pragma warning restore 612, 618
        }
    }
}
