export const themeStyles = {
  // Auth/Login styles
  container: {
    width: '100vw',
    height: '100vh',
    backgroundColor: '#0B3C9B',
    display: 'flex',
    flexDirection: 'column',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    margin: 0,
    padding: 0,
    overflow: 'hidden',
  },
  topBrandSection: {
    padding: '40px 24px 28px 24px',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  logoBox: {
    width: '48px',
    height: '48px',
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: '12px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#ffffff',
    fontSize: '24px',
    fontWeight: 'bold',
  },
  mainHeading: {
    color: '#ffffff',
    fontSize: '28px',
    fontWeight: '700',
    lineHeight: '1.2',
    margin: 0,
  },
  subText: {
    color: '#A3C1F7',
    fontSize: '14px',
    lineHeight: '1.4',
    margin: 0,
  },
  badgeRow: {
    display: 'flex',
    gap: '16px',
    marginTop: '4px',
  },
  badgeItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    color: '#ffffff',
    fontSize: '11px',
    opacity: 0.9,
  },
  formSheetModal: {
    flex: 1,
    backgroundColor: '#ffffff',
    borderTopLeftRadius: '28px',
    borderTopRightRadius: '28px',
    padding: '32px 24px',
    overflowY: 'auto',
  },
  formTitle: {
    fontSize: '18px',
    fontWeight: '700',
    color: '#1E293B',
    margin: '0 0 4px 0',
  },
  formSubTitle: {
    fontSize: '13px',
    color: '#64748B',
    margin: '0 0 24px 0',
  },
  inputGroup: {
    marginBottom: '18px',
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  fieldLabel: {
    fontSize: '12px',
    fontWeight: '600',
    color: '#475569',
    textTransform: 'uppercase',
    letterSpacing: '0.025em',
  },
  textInput: {
    width: '100%',
    padding: '12px 14px',
    borderRadius: '8px',
    border: '1px solid #CBD5E1',
    fontSize: '14px',
    color: '#1E293B',
    outline: 'none',
    boxSizing: 'border-box',
    backgroundColor: '#F8FAFC',
  },
  phoneInputContainer: {
    display: 'flex',
    alignItems: 'center',
    border: '1px solid #CBD5E1',
    borderRadius: '8px',
    padding: '0 12px',
    backgroundColor: '#ffffff',
  },
  countryCode: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#475569',
    marginRight: '12px',
    borderRight: '1px solid #E2E8F0',
    paddingRight: '12px',
  },
  phoneField: {
    flex: 1,
    padding: '12px 0',
    border: 'none',
    backgroundColor: 'transparent',
    outline: 'none',
    fontSize: '14px',
    color: '#1E293B',
    fontWeight: '600',
  },
  primaryBtn: {
    width: '100%',
    padding: '14px',
    borderRadius: '8px',
    backgroundColor: '#0D6EFD',
    color: '#ffffff',
    fontWeight: '600',
    fontSize: '14px',
    border: 'none',
    cursor: 'pointer',
    textAlign: 'center',
    marginTop: '8px',
    transition: 'opacity 0.2s',
  },
  secondaryBtn: {
    width: '100%',
    padding: '12px',
    borderRadius: '8px',
    border: '1px solid #0D6EFD',
    backgroundColor: 'transparent',
    color: '#0D6EFD',
    fontWeight: '600',
    fontSize: '13px',
    cursor: 'pointer',
    marginTop: '10px',
  },
  switchViewText: {
    textAlign: 'center',
    fontSize: '13px',
    color: '#64748B',
    marginTop: '20px',
  },
  toggleLink: {
    color: '#0D6EFD',
    fontWeight: 'bold',
    background: 'none',
    border: 'none',
    padding: 0,
    marginLeft: '4px',
    cursor: 'pointer',
    textDecoration: 'underline',
  },

  // Dashboard styles
  authDashboardContainer: {
    width: '100vw',
    height: '100vh',
    backgroundColor: '#f4f6f9',
    display: 'flex',
    flexDirection: 'column',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    margin: 0,
    padding: 0,
    overflow: 'hidden',
  },
  authHeader: {
    backgroundColor: '#0B3C9B',
    padding: '10px 16px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    height: '52px',
    boxSizing: 'border-box',
    flexShrink: 0,
  },
  logoutIconBtn: {
    background: 'rgba(255,255,255,0.15)',
    border: 'none',
    color: '#ffffff',
    padding: '6px 12px',
    borderRadius: '20px',
    fontSize: '12px',
    cursor: 'pointer',
    fontWeight: '600',
    display: 'flex',
    alignItems: 'center',
  },
  contentCardBody: {
    backgroundColor: '#f4f6f9',
    padding: '16px',
    borderRadius: '16px 16px 0 0',
    flex: 1,
    minHeight: 0,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  stickyActionZone: {
    flexShrink: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    paddingBottom: '14px',
  },
  actionAddBtn: {
    width: '100%',
    backgroundColor: '#0B3C9B',
    color: '#ffffff',
    border: 'none',
    padding: '13px',
    borderRadius: '12px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    textAlign: 'center',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
    boxShadow: '0 4px 10px rgba(11, 60, 155, 0.22)',
  },
  searchBarContainer: {
    position: 'relative',
  },
  searchField: {
    width: '100%',
    padding: '12px 14px 12px 40px',
    backgroundColor: '#ffffff',
    border: '1px solid #E2E8F0',
    borderRadius: '12px',
    fontSize: '14px',
    outline: 'none',
    boxSizing: 'border-box',
    color: '#1E293B',
  },
  searchIconMarker: {
    position: 'absolute',
    left: '14px',
    top: '50%',
    transform: 'translateY(-50%)',
    color: '#94A3B8',
    fontSize: '14px',
  },
  projectDropdown: {
    padding: '0 10px',
    backgroundColor: '#ffffff',
    border: '1px solid #E2E8F0',
    borderRadius: '12px',
    fontSize: '13px',
    outline: 'none',
    color: '#1E293B',
    maxWidth: '130px',
    height: '44px',
  },
  sortSelect: {
    padding: '6px 8px',
    backgroundColor: '#ffffff',
    border: '1px solid #E2E8F0',
    borderRadius: '8px',
    fontSize: '12px',
    outline: 'none',
    color: '#475569',
    fontWeight: '600',
    cursor: 'pointer',
  },
  sectionMetaRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '12px',
    flexShrink: 0,
  },
  sectionLabel: {
    fontSize: '16px',
    fontWeight: '700',
    color: '#1E293B',
    margin: 0,
  },
  projectsScrollArea: {
    flex: 1,
    minHeight: 0,
    overflowY: 'auto',
    paddingBottom: '72px',
  },
  worksiteCard: {
    backgroundColor: '#ffffff',
    borderRadius: '16px',
    padding: '16px',
    boxShadow: '0 2px 4px rgba(0,0,0,0.02)',
    marginBottom: '14px',
    border: '1px solid #F1F5F9',
  },
  cardHeadingRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    marginBottom: '8px',
  },
  siteIconWrapper: {
    width: '36px',
    height: '36px',
    borderRadius: '8px',
    backgroundColor: '#F1F5F9',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '18px',
    color: '#475569',
  },
  siteTitle: {
    fontSize: '15px',
    fontWeight: '700',
    color: '#1E293B',
    margin: 0,
    flex: 1,
  },
  arrowNavIndicator: {
    color: '#94A3B8',
    fontSize: '14px',
  },
  metricsGridRow: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr 1.2fr',
    gap: '8px',
    marginBottom: '6px',
  },
  metricCell: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
  },
  metricValue: {
    fontSize: '16px',
    fontWeight: '700',
    color: '#1E293B',
    margin: 0,
    lineHeight: '1.2',
  },
  metricValueDue: {
    fontSize: '16px',
    fontWeight: '700',
    color: '#DC2626',
    margin: 0,
    lineHeight: '1.2',
  },
  metricLabelText: {
    fontSize: '11px',
    color: '#94A3B8',
    fontWeight: '500',
    lineHeight: '1.2',
  },

  // Bottom Nav styles
  bottomDockNavBar: {
    position: 'fixed',
    bottom: 0,
    left: 0,
    width: '100%',
    height: '64px',
    backgroundColor: '#ffffff',
    borderTop: '1px solid #E2E8F0',
    display: 'flex',
    justifyContent: 'space-around',
    alignItems: 'center',
    boxSizing: 'border-box',
    zIndex: 1600,
  },
  navItemTab: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '4px',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: '#94A3B8',
  },
  navItemTabActive: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '4px',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: '#0B3C9B',
  },
  navTabIcon: {
    fontSize: '18px',
  },
  navTabLabel: {
    fontSize: '10px',
    fontWeight: '600',
  },
};